<script lang="ts" setup>
import { computed, ref } from '@vue/reactivity';
import { useBaseStore, useFormatter } from '@/stores';
import TxsInBlocksChart from '@/components/charts/TxsInBlocksChart.vue';

const props = defineProps(['chain']);

const tab = ref('blocks');
const base = useBaseStore();
const format = useFormatter();

const list = computed(() => base.recents);
</script>

<template>
  <div>
    <div class="tabs tabs-boxed bg-transparent mb-4">
      <a
        class="tab text-gray-400 uppercase"
        :class="{ 'tab-active': tab === 'blocks' }"
        @click="tab = 'blocks'"
      >
        {{ $t('block.recent') }}
      </a>
      <RouterLink
        class="tab text-gray-400 uppercase"
        :to="`/${chain}/block/${Number(base.latest?.block?.header.height || 0) + 10000}`"
      >
        {{ $t('block.future') }}
      </RouterLink>
    </div>

    <div v-show="tab === 'blocks'">
      <TxsInBlocksChart />

      <div class="overflow-x-auto mt-4 rounded bg-base-100 shadow">
        <table class="table table-compact w-full">
          <thead>
            <tr class="bg-gray-50 dark:bg-[#1c2234]">
              <th>Block Height</th>
              <th>Age</th>
              <th>Generated By</th>
              <th>Transactions</th>
                <th>Round	
</th>
        
              <th>hash	
</th>

   
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in list" :key="item.block.header.height" class="hover">
              <td>
                <RouterLink
                  class="link link-primary no-underline"
                  :to="`/${chain}/block/${item.block.header.height}`"
                >
                  {{ item.block.header.height }}
                </RouterLink>
              </td>
              <td>{{ format.toDay(item.block?.header?.time, 'from') }}</td>
              <td>
                
                  {{ format.validator(item.block?.header?.proposer_address) }}
            
              </td>
              
              <td>{{ item.block?.data?.txs.length || 0 }}</td>
            <td>{{ item.block?.last_commit?.round}}</td>
              <td>
                
                <div class="text-xs text-gray-400">   {{ item.block_id.hash }}</div>
              </td>
 
             
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<route>
{
  meta: {
    i18n: 'blocks',
    order: 5
  }
}
</route>
